apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: whoami
  namespace: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  selector:
    matchLabels:
      app: traefiklabs
      name: whoami
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s