apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: traefiklabs
    task: whoami